doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            price: 'App\Types\PriceType'

    orm:
        naming_strategy: 'doctrine.orm.naming_strategy.underscore_number_aware'
        mappings:
            App:
                type: 'annotation'
                dir: '%kernel.project_dir%/src/Entity/'
                prefix: 'App\Entity'
                is_bundle: false
